# Generated by Django 5.0.12 on 2025-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
    ]
