# Generated by Django 5.0.12 on 2025-02-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblAcopiador',
            fields=[
                ('intAcopiadorId', models.AutoField(primary_key=True, serialize=False)),
                ('intRUC', models.IntegerField(max_length=8)),
                ('strAcopiador', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tblCliente',
            fields=[
                ('intClienteId', models.AutoField(primary_key=True, serialize=False)),
                ('strTipo', models.CharField(max_length=11)),
                ('strSubTipo', models.CharField(max_length=11)),
                ('intRUC', models.IntegerField(max_length=8)),
                ('strRazon', models.CharField(max_length=11)),
                ('strDireccion', models.CharField(max_length=50)),
                ('intTelefono', models.IntegerField(max_length=12)),
                ('fltFactorPeso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('intPesadorCreacionId', models.IntegerField(null=True)),
                ('dtFechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('intPesadorModificacionId', models.IntegerField(null=True)),
                ('dtFechaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblEstado',
            fields=[
                ('intEstadoId', models.AutoField(primary_key=True, serialize=False)),
                ('strEstado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tblPesador',
            fields=[
                ('intPesadorId', models.AutoField(primary_key=True, serialize=False)),
                ('strNombres', models.CharField(max_length=255)),
                ('strApellidos', models.CharField(max_length=255)),
                ('strLogin', models.CharField(max_length=100)),
                ('strPwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tblPlataforma',
            fields=[
                ('intPlataformaId', models.AutoField(primary_key=True, serialize=False)),
                ('strPlataforma', models.CharField(max_length=255)),
                ('strRUC', models.CharField(max_length=20)),
                ('strDireccion', models.CharField(max_length=255)),
                ('intEstadoDefault', models.IntegerField()),
                ('bitRegistroDefault', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='tblProcedencia',
            fields=[
                ('intProcedenciaId', models.AutoField(primary_key=True, serialize=False)),
                ('strProcedencia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tblProducto',
            fields=[
                ('intProductoId', models.AutoField(primary_key=True, serialize=False)),
                ('strProducto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tblTarifa',
            fields=[
                ('intTarifaId', models.AutoField(primary_key=True, serialize=False)),
                ('strTarifa', models.CharField(max_length=255)),
                ('strMoneda', models.CharField(max_length=10)),
                ('intMonto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='tblTransportista',
            fields=[
                ('intTransportistaId', models.AutoField(primary_key=True, serialize=False)),
                ('strTransportista', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tblZona',
            fields=[
                ('intZonaId', models.AutoField(primary_key=True, serialize=False)),
                ('strZona', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tblCertificado',
            fields=[
                ('intCertificadoId', models.AutoField(primary_key=True, serialize=False)),
                ('strCertificado', models.CharField(max_length=255)),
                ('intPlataformaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanza.tblplataforma')),
            ],
        ),
        migrations.CreateModel(
            name='tblEntrada',
            fields=[
                ('intEntradaId', models.AutoField(primary_key=True, serialize=False)),
                ('strGuia', models.CharField(max_length=50)),
                ('strPlaca', models.CharField(max_length=20)),
                ('dtFechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('dtFechaModificacion', models.DateTimeField(auto_now=True)),
                ('intCertificadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanza.tblcertificado')),
                ('intClienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanza.tblcliente')),
                ('intEstadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanza.tblestado')),
                ('intProductoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanza.tblproducto')),
            ],
        ),
        migrations.CreateModel(
            name='tblSalida',
            fields=[
                ('intSalidaId', models.AutoField(primary_key=True, serialize=False)),
                ('dtFechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('dtFechaModificacion', models.DateTimeField(auto_now=True)),
                ('intEntradaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanza.tblentrada')),
                ('intEstadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanza.tblestado')),
            ],
        ),
        migrations.CreateModel(
            name='tblSerieDoc',
            fields=[
                ('intSerieDocId', models.AutoField(primary_key=True, serialize=False)),
                ('strSerieDoc', models.CharField(max_length=50)),
                ('intCertificadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanza.tblcertificado')),
            ],
        ),
        migrations.AddField(
            model_name='tblentrada',
            name='strSerieDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanza.tblseriedoc'),
        ),
        migrations.AddField(
            model_name='tblentrada',
            name='intTransportistaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanza.tbltransportista'),
        ),
    ]
