# Generated by Django 5.0.12 on 2025-02-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblacopiador',
            table='tblAcopiador',
        ),
        migrations.AlterModelTable(
            name='tblcertificado',
            table='tblCertificado',
        ),
        migrations.AlterModelTable(
            name='tblcliente',
            table='tblCliente',
        ),
        migrations.AlterModelTable(
            name='tblentrada',
            table='tblEntrada',
        ),
        migrations.AlterModelTable(
            name='tblestado',
            table='tblEstado',
        ),
        migrations.AlterModelTable(
            name='tblpesador',
            table='tblPesador',
        ),
        migrations.AlterModelTable(
            name='tblplataforma',
            table='tblPlataforma',
        ),
        migrations.AlterModelTable(
            name='tblprocedencia',
            table='tblProcedencia',
        ),
        migrations.AlterModelTable(
            name='tblproducto',
            table='tblProducto',
        ),
        migrations.AlterModelTable(
            name='tblsalida',
            table='tblSalida',
        ),
        migrations.AlterModelTable(
            name='tblseriedoc',
            table='tblSerieDoc',
        ),
        migrations.AlterModelTable(
            name='tbltarifa',
            table='tblTarifa',
        ),
        migrations.AlterModelTable(
            name='tbltransportista',
            table='tblTransportista',
        ),
        migrations.AlterModelTable(
            name='tblzona',
            table='tblZona',
        ),
    ]
