# Generated by Django 5.0.12 on 2025-02-14 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0002_tblatencionclte_tblpersseguridad_tblsupervcancha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblentrada',
            name='intNumDoc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tblentrada',
            name='strSerieDocAbrev',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='tblTicketPesaje',
            fields=[
                ('intTicketPesajeId', models.AutoField(primary_key=True, serialize=False)),
                ('intEntrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanza.tblentrada')),
            ],
        ),
    ]
