# Generated by Django 5.0.12 on 2025-02-14 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0003_tblentrada_intnumdoc_tblentrada_strseriedocabrev_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblticketpesaje',
            table='tblTicketPesaje',
        ),
    ]
